create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
create table categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table order_items (quantity integer, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2), id bigint not null auto_increment, order_date datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table products (price decimal(38,2), category_id bigint, id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table if exists order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table if exists order_items add constraint FKocimc7dtr037rh4ls4l95nlfi foreign key (product_id) references products (id);
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories (id);
